implement flu season property
vaccineontology/VO pull request #738
Opened 2024-08-23 18:54 UTC by xingxianli

1. add term VO:0010395 flu season
2. add 'has flu season'
3. add different flu season terms, ie: '2018-2019'
4. add flu season column in vaccine.csv
5. delete repeated sheet 'src/views/vo_new_terms_IDs.xlsx', keep '[src/vo_new_terms_IDs.xlsx]'

2024-08-26 03:00 UTC, zhengj2007 requested changes
1. Need consider to rename the flu season individuals, e.g. 2013-2014 -> flu season 2013-2014. If we use '2013-2014', '2016', it is not clear what the number mean.
2. Need to add intermediate flu season terms, such as 'human influenza virus vaccine 2013-2014'. For each flu seasons, need have a corresponding human influenza virus vaccine.
Add 'licensed human influenza virus vaccine', a subClassOf 'human influenza virus vaccine' = 'human influenza virus vaccine' and has_role some 'licensed vaccine role'
 'human influenza virus vaccine 2013-2014' and all other intermediate flu season terms are subClassOf 'licensed human influenza virus vaccine'
e.g. 'human influenza virus vaccine 2013-2014' = 'licensed human influenza virus vaccine' and has_flu season some 'flu season 2013-2014'

2024-08-26 19:05 UTC, xingxianli commented
Hi Dr Zheng, I changed the file based on your comments.

2024-08-26 20:08 UTC, zhengj2007 commented
@xingxianli 
Some vaccine missed flu season axioms, for example,
VO_0019103 synonym is 'influenza virus vaccine 2016-2017 (quadrivalent - California/Hong Kong/Brisbane/Phuket) 0.1 ML Prefilled Syringe', flu season 2016-2017
May replace term label with Rxnorm synonym, replace 'RxNorm preferred name' with term label.
If term label and Rxnorm synonym are same, replace 'RxNorm preferred name'  with 'Rxnorm synonym'

Besides, some defined classes do not look correct. 
For example, VO_0020020 should be inferred as VO_0020298 'Afluria 2010-2011 Formula vaccine'

2024-09-03 16:29 UTC, zhengj2007 approved these changes

2024-09-03 16:29 UTC, merged